// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package di

import (
	"github.com/gorilla/sessions"
	"github.com/n-creativesystem/ncsfw/config"
	"github.com/n-creativesystem/ncsfw/handler"
	"github.com/n-creativesystem/ncsfw/social"
)

// Injectors from wire.go:

func Init(store sessions.Store) (*Injector, error) {
	configConfig := config.NewConfig()
	socialService := social.ProvideService(configConfig)
	socialLoginImpl := handler.NewSocialLogin()
	socialHandler := handler.NewSocialHandler(configConfig, socialService, store, socialLoginImpl)
	injector := Injection(configConfig, socialService, socialHandler)
	return injector, nil
}
